#!/bin/bash
#
# /bin/sh replacement for startup
#

ulimit -c unlimited

# grab the port number
port=8006
if [ "$1" != "" ]; then port=$1; fi

# set up
cd ../area
if [ -e shutdown.txt ]; then mv shutdown.txt shutdown2.txt; fi
if [ -e current.txt ]; then mv current.txt current2.txt; fi

# allow cores
# ulimit -c 50000
# stack limit
# ulimit -s 1500

# renice +5 -p $$
# loop indefinately
while :
do
  # find a logfile

  index=1000
  while :
  do
    logfile=../log/$index.log
    if [ ! -e $logfile ]; then break; fi
    let index=$index+1
  done

 if [ -e core.* ]; then 
        gdb -batch -x ../system/gdbcommands ../src/ack core.* > coremail 
# commented out rm core.* line so i could troubleshoot since email part is broke# -klinks	
#	rm core.*
#       mail "mike+aowcrash@mikehmayer.com" -s "AoW Crash" < coremail # Send Akuji the broken shiznit 
#	mail "whitten@email.com" -s "AoW Crash" < coremail #Send to Stilicho
#       mail "adlorin@gmail.com" -s "AoW Crash con core" < coremail
#        mail "klink8@hotmail.com" -s "AoW Crash" < coremail #Send to Klinks  
    fi

  # run the mud
  ../src/ack $port >$logfile 2>&1

  # shutdown?


  if [ -e shutdown.txt ]; then
    echo "startup: shutting down" >>$logfile
    exit 1
  fi
  
  # sleep, so if we fail on boot we don't get massive looping
  sleep 15
done
